"""empty message

Revision ID: 767f12357949
Revises: 580ea5b73255
Create Date: 2025-12-14 19:47:09.059222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '767f12357949'
down_revision = '580ea5b73255'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('budget', schema=None) as batch_op:
        batch_op.add_column(sa.Column('spent', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('budget', schema=None) as batch_op:
        batch_op.drop_column('spent')

    # ### end Alembic commands ###
